### ISSUE TITLE
Cannot properly open files in the editor

### ISSUE THREAD

**Issue by vbmacher** [vbmacher/emuStudio#149]
Tested on JDK 11, Windows 10. Opening ends up with exception (which is not logged):

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class javax.swing.text.AbstractDocument$DefaultDocumentEventUndoableWrapper cannot be cast to class javax.swing.text.AbstractDocument$DefaultDocumentEvent (javax.swing.text.AbstractDocument$DefaultDocumentEventUndoableWrapper and javax.swing.text.AbstractDocument$DefaultDocumentEvent are in module java.desktop of loader 'bootstrap')
        at emustudio.gui.editor.EmuTextPane$2.undoableEditHappened(EmuTextPane.java:182)
        at java.desktop/javax.swing.text.AbstractDocument.fireUndoableEditUpdate(AbstractDocument.java:293)
        at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:761)
        at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
        at java.desktop/javax.swing.text.DefaultEditorKit.read(DefaultEditorKit.java:239)
        at emustudio.gui.editor.EmuTextPane.openFile(EmuTextPane.java:368)
        at emustudio.gui.editor.EmuTextPane.openFileDialog(EmuTextPane.java:433)
...
```

Tested on MITS Altair 8800, opened any file with more lines.

**Comment by vbmacher** [comment]
This issue is caused by catching `UndoableEdit`s. In emuStudio, edits which represent style changes (by syntax highlighter) are not captured in the undo stack. In JDK 8 and lower, the edit itself could be casted to `AbstractDocument.DefaultDocumentEvent` from which it could be detected if it was a style change or not.

The problem is that as of JDK 9 and above, the edit is wrapped with `AbstractDocument.DefaultDocumentEventUndoableWrapper`, which is private and cannot be accessed without reflection.

**Comment by vbmacher** [comment]
The "fix" above uses reflection in case the edit could not be casted to `DefaultDocumentEvent`. However, if the reflection is still not successful, then the undo/redo capability is completely disabled.

Proper solution would be to completely rewrite the editor to not use undoable style changes, but has custom renderer, like in [here](https://git.iem.at/sciss/SyntaxPane).
