### ISSUE TITLE
ADM-3A terminal cannot load custom font

### ISSUE THREAD

**Issue by vbmacher** [vbmacher/emuStudio#77]
```
19:32:44.805 [main] ERROR n.s.e.d.adm3a.gui.TerminalWindow - Cannot load custom font file, using Java monospace
java.awt.FontFormatException: bad table, tag=28
	at sun.font.TrueTypeFont.init(TrueTypeFont.java:547) ~[na:1.7.0_71]
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:191) ~[na:1.7.0_71]
	at sun.font.SunFontManager.createFont2D(SunFontManager.java:2461) ~[na:1.7.0_71]
	at java.awt.Font.<init>(Font.java:614) ~[na:1.7.0_71]
	at java.awt.Font.createFont0(Font.java:968) ~[na:1.7.0_71]
	at java.awt.Font.createFont(Font.java:876) ~[na:1.7.0_71]
	at net.sf.emustudio.devices.adm3a.gui.TerminalWindow.<init>(TerminalWindow.java:49) ~[adm3A-terminal.jar!/:na]
	at net.sf.emustudio.devices.adm3a.impl.TerminalImpl.initialize(TerminalImpl.java:87) [adm3A-terminal.jar!/:na]
	at emustudio.architecture.Computer.initialize(Computer.java:158) [classes/:na]
	at emustudio.main.Main.main(Main.java:170) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
```

**Comment by vbmacher** [comment]
It is caused by maven resources plugin, it stupidly filters binary files.
