### ISSUE TITLE
Finish implementation of automatic emulation

### ISSUE THREAD

**Issue by vbmacher** [vbmacher/emuStudio#81]
All supported virtual computers must support emulation automation. In the 0.39 version, the automation should be implemented individually per-project. In future versions, there might exist some automation API.

I know that RAM machine does not support it well, and this must be tested also for other computers (e.g. brainduck).

**Comment by vbmacher** [comment]
After running:

```
java -jar emuStudio.jar --auto --nogui --config RAM --input examples/ra-ram/factorial.ram 
```

There is an exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.clear(Collections.java:1466)
	at emustudio.architecture.SettingsManagerImpl.destroy(SettingsManagerImpl.java:72)
	at emustudio.main.Automatization.run(Automatization.java:246)
	at emustudio.main.Main.runAutomation(Main.java:101)
	at emustudio.main.Main.main(Main.java:92)
```

**Comment by vbmacher** [comment]
File names of abstract tapes should be valid file names; and in lower-case. All spaces should be replaced with `_` char.

**Comment by vbmacher** [comment]
RAM computer automation now works as expected.

**Comment by vbmacher** [comment]
BrainDuck terminal does not support automatic emulation

**Comment by vbmacher** [comment]
BrainDuck terminal now *requires* that both files:

- `brainduck-terminal.in`
- `brainduck-terminal.out`

must exist if `nogui` flag is set.

**Comment by vbmacher** [comment]
Automatic emulation tested and works for:
- MITS Altair 8800
- MITS Altair 8800 (Z80)
- RAM
- RASP
- BrainDuck

The only computer which needs to be tested is SSEM.

**Comment by vbmacher** [comment]
SSEM does not work. Running with:

```
$ java -jar emuStudio.jar --config "SSEM" --auto --nogui --input examples/as-ssem/the-fraj.ssem 
```

gives

```
2017-01-18 10:41:37,534 [ERROR][e.m.Emulator] Unexpected error
java.lang.NullPointerException: null
	at net.sf.emustudio.ssem.display.DisplaySSEM.reset(DisplaySSEM.java:80)
	at java.util.HashMap$Values.forEach(HashMap.java:980)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at emustudio.architecture.Computer.resetPlugins(Computer.java:135)
	at emustudio.architecture.Computer.initialize(Computer.java:131)
	at emustudio.main.Emulator.load(Emulator.java:73)
	at emustudio.main.Main.main(Main.java:80)
2017-01-18 10:41:37,534 [ERROR][e.m.Main] Error: Error: Could not initialize emuLib. Please see log file for details.
```

**Comment by vbmacher** [comment]
Also question is, *what* should be the output of the SSEM. Memory content? Together with values of registers? Could be. Then SSEM CPU should implement the automatic emulation instead of terminal.
